AllCops:
  Exclude:
    - Capfile
    - Gemfile
    - Rakefile
    - bin/**/*
    - tmp/**/*

  Include:
    - app/**/*.rb
    - lib/**/*.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/services/acme/csv_parser.rb
